name: CI MLFlow Train

on:
  push:
    paths:
      - "MLProject/**"
      - ".github/workflows/preprocess.yml"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: Workflow-CI/MLProject/conda.yaml
          activate-environment: mlflow-env

      - name: Install MLflow
        run: pip install mlflow

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --no-conda
